### PR TITLE
Fixed url on distance calculator

### LINKED ISSUE #13: Fix url on distance calculator
If some fields are incorrect or empty, the URL changes and gets invalid

url-snowflake-distance

### PR DESCRIPTION
**Pull request by AFink**
Fixed #13 by adding an additional variable that doesn't show the placeholder (-) from the URL.

Signed-off-by: Andreas Fink <andreas@andreasfink.xyz>

### CODE REVIEW

File: app/Http/Livewire/Snowflake/Distance.php [hunk 1]
```diff
@@ -16,9 +17,9 @@ class Distance extends Component
 
     public function processSnowflake()
     {
-        $this->resetExcept(['snowflake1', 'snowflake2']);
+        $this->resetExcept(['snowflake1', 'snowflake1Display', 'snowflake2']);
 
-        if($this->snowflake1 == null || $this->snowflake2 == null) return;
+        if($this->snowflake1 == '-' || $this->snowflake1Display == null || $this->snowflake2 == null) return;
```
Comment (fbrettnich) [inline app/Http/Livewire/Snowflake/Distance.php:22]:
```suggestion
        if($this->snowflake1 == null || $this->snowflake1 == '-' || $this->snowflake1Display == null || $this->snowflake2 == null) return;
```
